### ISSUE TITLE
[Verified] Posting a picture doesn't show it until refresh.

### ISSUE THREAD

**Issue by berkus** [pepyatka/pepyatka-html#512] opened 2015-06-26 10:15 UTC
See
https://freefeed.net/bugreport/e71651f2-9eb5-47d9-b642-8f7456d6a1bf?offset=0

**Comment by clbn** [comment] 2015-06-26 10:26
I saw this once on freefeed.net, but cannot reproduce on micropeppa or on my instance.

**Comment by berkus** [comment] 2015-06-26 11:07
Looks like it's reliably reproducible for @davidmz

**Comment by clbn** [comment] 2015-07-09 16:10
Fixed in #548.

**Closed as completed by clbn** 2015-07-09 16:10 UTC
Labels: bug, a-user-reported, user-p2

**Comment by smallq-git** [comment] 2015-07-14 19:02
Does not happen anymore
