### ISSUE TITLE
[Duplicate] Attach: must be able to remove selected files when in New Post mode

### ISSUE THREAD

**Issue by urbansheep** [pepyatka/pepyatka-html#623] opened 2015-08-03 22:15 UTC
Currently there's no way to remove erroneously attached files on the new post except abandoning post completely. This may be inconvenient when user had to choose many pictures or several music tracks just to start over after clicking wrong file in the file picker.

There should be an option to remove files with a click after they were added to the post form.
- Images: click on image summons confirmation “Are you sure you want to get rid of this picture?” → Yes removes image, Cancel dismisses.
- Files: After the file name there should appear a link “Remove”, which also displays an inline confirmation request when clicked “Are you sure you want to get rid of this file?”

**Comment by smallq-git** [comment] 2015-08-04 20:32
duplicate of https://github.com/pepyatka/pepyatka-html/issues/584

**Closed as completed by smallq-git** 2015-08-04 20:32 UTC
Labels: enhancement
