### ISSUE TITLE
"Home" on an after-subscribe page has a wrong URL

### ISSUE THREAD

**Issue by earlyadopter** [pepyatka/pepyatka-html#170] opened 2015-04-16 18:29 UTC
After clicking Subscribe link on somebody's else page an "empty" page is displayed (with regular links to Home, etc.) "Home" link on that "empty" page has URL domain/#/about, not domain/my_own_username.

**Comment by epicmonkey** [comment] 2015-04-16 21:45
Isn't it dup of https://github.com/pepyatka/pepyatka-html/issues/112?

**Comment by epicmonkey** [comment] 2015-04-20 14:33
Closing as a duplicate of #112.

**Closed by epicmonkey** 2015-04-20 14:33 UTC
Labels: blocker, bug, question
