### ISSUE TITLE
Hide information is not retained

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#267] opened 2015-04-26 21:53 UTC
1. Log in.
2. Hide a post.
3. Refresh page.

Expected: hidden posts remain hidden.
Actual: hidden posts are shown again.

**Comment by epicmonkey** [comment] 2015-04-28 22:53
Resolved in https://github.com/pepyatka/pepyatka-server/commit/ed957f5. This is a regression caused by https://github.com/pepyatka/pepyatka-server/commit/36d662f35f7dbfb5994d49a3e5bbce3ee9037e2a.

**Closed by epicmonkey** 2015-04-28 22:53 UTC
Labels: bug
